version: '3.7'

services:
  awesome_blog:
    image: awesome-blog:latest
    build:
      context: .
      network: host
    restart: always
    volumes:
      - ./src:/usr/app/src # for watch mode in development
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
      MAIL_SERVER_HOST: fakesmtp
      MAIL_SERVER_PORT: 25
    ports:
      - 1234:3000
    networks: 
      fntch-unit-test:

  postgres: 
    image: postgres:15
    expose:
      - 5432
    restart: always
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    networks:
      fntch-unit-test:

  fakesmtp:
    image: hatamiarash7/fake-smtp:latest
    expose:
      - 25
    volumes:
      - fakesmtp:/output
    networks:
      fntch-unit-test:

volumes:
  postgres:
  fakesmtp:

networks:
  fntch-unit-test:
